### ISSUE TITLE
Experimental release filenames use backslashes instead of forward slashes

### ISSUE THREAD

**Issue by irasanchez** [jk-oster/obsidian-search-for-web#6]
This causes an error when trying to "load unpacked" extensions, due to the subdirectories not being created. The browser then can't recognize the `dist` directory or the manifest.json file.

Simple manual fix in the meantime though.

Edit: 

I am not certain this is caused by the backslashes after manually fixing the problem. I just know that, even after extracting, all subdirectories were flattened still, and I had to go in to make them and rename the files. Mac OS Ventura, Safari.

**Comment by jk-oster** [comment]
Thank you for your feedback!

Maybe there was some issue when you unpacked it / compiled it with vite?

The new released version now for sure should be using forward slash.

I develop the extension on windows, so there might be some incompatibilities I am not aware of.
